### ISSUE TITLE
Quais seriam as funções mais básicas?

### ISSUE THREAD

**Issue by alexandre-mbm** [nfephp-org/sped-esocial#10]
Eu busco uma forma de baixar programaticamente guias, recibos e relatórios. Encontrei?

**Comment by robmachado** [comment]
Alexandre; esse projeto ainda está em fase de estruturação não existe ainda nada codificado ou funcional porque o eSocial ainda não disponibilizou nenhum webservice para homologação, eles ainda estão construindo as estruturas e regras, mas ainda não liberaram nada além de alguns documentos básicos e definições de estrutura de dados das mensagens (XSD), esse projeto deverá começar a andar apenas a partir do inicio de 2017, isso se houver interessados em colaborar (com trabalho e/ou por doações).
A ideia é montar um framework para acessar TODOS os serviços fornecidos pelo eSocial, usando PHP puro.

**Comment by alexandre-mbm** [comment]
>  A ideia é montar um framework para acessar TODOS os serviços fornecidos pelo eSocial, usando PHP puro.

Que tipo de coisas receberá prioridade?

**Comment by robmachado** [comment]
Isso ainda não foi definido, mas com certeza as prioridades são aquelas que serão exigidas por todas as empresas e com certeza relacionadas com os métodos do webservice. Mas não temos nada estabelecido ainda. Quando iniciarmos, devemos colocar essas prioridades dentro do MILESTONE desse projeto e a partir deles abrir ISSUES para cada processo. E antecipo que serão DEZENAS.
