### ISSUE TITLE
Erro SoapBase.php - saveDebugFiles 

### ISSUE THREAD

**Issue by edsonalanis** [nfephp-org/sped-esocial#135]
Ao habilitar o debug no envio do Soap ocorreu o erro abaixo:
![image](https://user-images.githubusercontent.com/6743202/32375264-22369058-c088-11e7-8c34-ae6c934537f7.png)

Para resolver isto tive que fazer esta alteração no código:

-  **de**: $now            = \DateTime::createFromFormat('U.u', microtime(true));
-  **para**: $now            = \DateTime::createFromFormat('U.u', number_format(microtime(true), 6, '.', ''));

**Comment by robmachado** [comment]
Obrigado Edson
Vou verificar ...

**Comment by robmachado** [comment]
Pode me dizer em que S.O. ocorreu o erro e qual a versão do PHP ?

**Comment by edsonalanis** [comment]
Eu utilizo o Windows 10 aqui na minha máquina

**Comment by robmachado** [comment]
Pois bem vou ser o comportamento em demais S.O., mas windows 10 não é, nem nunca será um ambiente adequado para desenvolver, instalar e rodar esse tipo de aplicação. Sugiro fortemente  o uso do Vargrant para o desenvolvimento ou melhor usando o DOCKER (acho que já existe para o Ruindows)

**Comment by edsonalanis** [comment]
Ok, entendo a sua posição porém este código, o qual agora pra mim está funcionando, foi retirado dos comentários da documentação do PHP.
Então não acredito se tratar de um problema do Windows ou não, até porque em nenhum lugar diz explicitamente que para programar em PHP dever utilizar o SO linux e não Windows.

![image](https://user-images.githubusercontent.com/6743202/32378608-5501eb9a-c092-11e7-8f7c-9bbb84eceaa7.png)

**Comment by robmachado** [comment]
Entendo !!
Corrigindo, e subindo nova TAG
Roberto

**Comment by robmachado** [comment]
Corrigido sped-common SoapBase::class, por favor atualize os pacotes

**Comment by edsonalanis** [comment]
Olá, fiz atualização dos pacotes e não veio a correção

**Comment by robmachado** [comment]
Realmente falha minha, subi em  sped-common e não na cópia que está em sped-esocial, já corrigido!

**Comment by robmachado** [comment]
Realmente falha minha, subi em  sped-common e não na cópia que está em sped-esocial, já corrigido!
