### ISSUE TITLE
Evento EvtAdmissao - Possui propriedade Sequencial

### ISSUE THREAD

**Issue by edsonalanis** [nfephp-org/sped-esocial#138]
O evento EvtAdmissao possui uma propriedade Sequencial e utiliza ela no toNode() para criar o Id, porém na classe base Factory já é feito a criação deste Id utilizando o $std->sequencial passado.
Olheis os demais eventos e todos eles não possuem esta codificação do EvtAdmissao, que está gerando um ID errado quando tenho mais de um evento na minha lista de eventos

**Comment by robmachado** [comment]
Opa Edson; sim não foi eu pessoalmente que criei todos os eventos teve um colega ajudando e ele fez de forma diferente do que eu custumo fazer. Estou sem tempo no momento mas terão de ser refatorados vários desses eventos para deixa-los  ajustados de forma adequada como EvtEmpregador e EvtPgtos os quais  fui eu quem fez e estão usando os NODES criados pela classe Factory.
O duro é arranjar tempo e ajuda com tempo para explicar como devem ser feitos os processos e eventos. Mas fico muito satisfeito por sua observação !!

**Comment by edsonalanis** [comment]
Olá se quiser posso ajudar a refatorar, este caso.
Só não sei fazer os commits, mas posso te passar por email a classe alterada

**Comment by robmachado** [comment]
Edson Poxa que legal, mas que tal eu te ajudar te mostrando como fazer o pull request. 
Eu teria muito prazer em fazer isso !

**Comment by edsonalanis** [comment]
pode ser, tenho medo de fazer errado heheh

**Comment by robmachado** [comment]
Corrigido !
