### ISSUE TITLE
Evento EvtInfoEmpregador - novavalidade - fimValid

### ISSUE THREAD

**Issue by edsonalanis** [nfephp-org/sped-esocial#139]
Encontrei um problema em alterar a informação do empregador no objeto novavalidade está dando erro no fimValid, acredito que sejam 3 erros:

1. Está incluindo a tag iniValid e deveria ser fimValid
2. Está pegando os dados do objecto com o nome errado $sh->fimValid e o correto seria $sh->fimvalid
3. Esta informação não é obrigatória, e da forma como está fica obrigatória

**Código atual**
`$this->dom->addChild(
                $novavalidade,
                "iniValid",
                $sh->fimValid,
                false
            );`

**Código ajustado e funcionando**
`$this->dom->addChild(
	            $novavalidade,
	            "fimValid",
	            ! empty($sh->fimvalid) ? $sh->fimvalid : '',
	            false
	        );`

**Comment by robmachado** [comment]
Muito bom obrigado assim que der faço a correção

**Comment by robmachado** [comment]
Edson; de onde você pegou essa informação ??? Pois no meu código está assim:

//periodo
        $idePeriodo = $this->dom->createElement("idePeriodo");
        $this->dom->addChild(
            $idePeriodo,
            "iniValid",
            $this->std->ideperiodo->inivalid,
            true
        );
        $this->dom->addChild(
            $idePeriodo,
            "fimValid",
            ! empty($this->std->ideperiodo->fimvalid) ? $this->std->ideperiodo->fimvalid : '',
            false
        );

**Comment by edsonalanis** [comment]
Este é o periodo o que estou falando é novavalidade para alteração

**Comment by robmachado** [comment]
heheh !!! CORRIGIDO, você tem toda razão meu amigo
