### ISSUE TITLE
Web Service

### ISSUE THREAD

**Issue by igorcoelho** [nfephp-org/sped-esocial#180]
Nunca trabalhei com web service antes. Gostaria de saber se essa API não tira a obrigatoriedade de ter um web service. Ou ela já tem o webservice acoplado?

**Comment by robmachado** [comment]
hã ?!?!?!?

A API é um meio para simplificar o acesso ao webservice da RECEITA.
Ela torna transparente as operações com o webservice da Receita, para quem não sabe ou não deseja montar todo o processo de comunicação SOAP sobre SSL

**Comment by igorcoelho** [comment]
Eu li no site da receita q cada empresa terá que ter um webservice próprio para se comunicar com o webservice deles. Com a utilização desta API eu ainda preciso ter um webservice próprio? Desculpe se não fui claro.

**Comment by robmachado** [comment]
Igor;
Não é necessário um WEBSERVICE para falar com outro !!!
O que eles informam é que você deve ter um aplicativo próprio para interagir com o webservice deles.
Como ocorre com a NFe, CTe, MDFe, eFinanceira, EFDReinf e por ai vai ....

**Comment by robmachado** [comment]
A API facilita o seu caminho ... muito que código que você teria de fazer já está na API para usar

**Comment by igorcoelho** [comment]
Basta eu rodar esse projeto no meu servidor que eu consigo enviar um evento fake para o servidor de produção restrita?

**Comment by robmachado** [comment]
Estude o codigo e ENTENDA como funciona 
Nenhum FAKE vai para lugar algum é FAKE !!! 
Se precisar de assessoria tem custo $$$

**Comment by igorcoelho** [comment]
Certo. Sou de empresa pública. Estou tentando reunir alternativas de solução com a minha equipe. Certamente irei estudar a API de vcs. Se for válida pra gente, eu espero que haja interesse mútuo de uma consultoria. Agradeço pelo seu feedback.

**Comment by robmachado** [comment]
Claro que sempre haverá enquanto a API for mantida, interesse em ajudar, independentemente de qualquer outra coisa. Por isso a mesma foi liberada como OpenSource.
