### ISSUE TITLE
Mudanças no ESocial 30/06

### ISSUE THREAD

**Issue by fabiozech** [nfephp-org/sped-esocial#182]
Houve alterações no Esocial na parte de SST dia 30/06.
E alterações dia 16/07 sobre Órgãos/Entes do Poder Público

NDE 01/2018 - Eventos de Segurança e Saúde no Trabalho - SST  - 30/05/2018 
NDE 02/2018 - Eventos relativos a Órgãos/Entes do Poder Público - 16/07/2018

**Comment by robmachado** [comment]
Estou acompanhando essas alterações. Ms por ora são PROPOSTAS ....

**Comment by fabiozech** [comment]
Olá Roberto, você chegou e ver a atualização dessa parte "NDE 01/2018 V.2.0 - EVENTOS DE SEGURANÇA E SAÚDE NO TRABALHO - SST - 14/09/2018"

**Comment by robmachado** [comment]
Sim já havia visto !! é muita mudança constantemente ... tá ficando difícil acompanhar
