### ISSUE TITLE
Problema/Dúvida no evento S-2300

### ISSUE THREAD

**Issue by Ronney** [nfephp-org/sped-esocial#188]
Estou tendo um problema no envio dos estagiários. Na versão  2.4.02 do layout diz q não devemos preencher a natureza da atividade nas categorias Diretor não empregado, servidor público indicado a conselho, membro de conselho titular e estagiário. Problema é q esse campo está como obrigatório na API. Para contornar o problema tive que ir no arquivo evtTSVInicio.schema e colocar como não requerido. Existe alguma outra forma de solucionar esse tipo de situação?

**Comment by robmachado** [comment]
Opa Ronney;
Claro é só abrir uma ISSUE relatando o problema. Como você já fez !!! :+1: 
Eu mesmo vou fazer essa correção
Nesses casos (e podem haver mais), o melhor caminho é alterar o https://github.com/nfephp-org/sped-esocial/blob/master/examples/schemes/v02_04_02/s2300_JsonSchemaEvtTSVInicio.php
Rodar o exemplo que um novo jsonShema será criado ! e ai é só subir o PR

**Comment by Ronney** [comment]
Muito obrigado pelos esclarecimentos. O "eSocial" é bastante rigoroso e está sujeito a mudar os campos e essas validações a qualquer hora, a Api está ajudando bastante.

**Comment by robmachado** [comment]
Você pode me passar a pagina do manual que contêm essa informação

**Comment by robmachado** [comment]
Se você se refere a regra REGRA_TSV_COMPATIBILIDADE_CLASSTRIB_CATEGORIA ela não permite simplesmente a NÃO existência do campo, apenas limita as suas possibilidades. Pelo que pude entender.

**Comment by Ronney** [comment]
Página 121

**Comment by robmachado** [comment]
OK grato providenciando a correção :+1:

**Comment by robmachado** [comment]
Alteração já disponivel
