### ISSUE TITLE
Erro ao usar "enviarLoteEventos"

### ISSUE THREAD

**Issue by mauriciomfilho** [nfephp-org/sped-esocial#226]
Ao usar o método para envio de lotes recebia o erro de que faltava o ID do evento.

"This XML is not valid. Element '{http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_1}evento', attribute 'Id': '' is not a valid value of the atomic type 'xs:ID'."

Notei que a linha 165 do Factory.php estava comentada; Removendo o comentário o método voltou a funcionar. 
  
https://github.com/nfephp-org/sped-esocial/blob/80940589e15030ad3ac058d8d587ed265690a6cc/src/Common/Factory.php#L165

**Comment by robmachado** [comment]
Corrigindo!
