### ISSUE TITLE
Não encontrei referência ao parâmetro 'tpaso' nos leiautes 2.0 e 2.5 do eSocial.

### ISSUE THREAD

**Issue by andredaniel** [nfephp-org/sped-esocial#228]
https://github.com/nfephp-org/sped-esocial/blob/6aef8f65fa71745e64ce4d6b1da146833c57aaff/examples/Fake/v02_05_00/Fake_s2220_EvtMonit.php#L45

**Comment by robmachado** [comment]
Tem razão !! estou removendo esse "ruido" do evento 
Obrigado !

**Comment by robmachado** [comment]
Resolvido!
