### ISSUE TITLE
s2210 evtCAT - Remoção do Campo tpRegistrador

### ISSUE THREAD

**Issue by maviniciuus** [nfephp-org/sped-esocial#231]
Com a atualização do eSocial, da versão 2.4.2 para 2.5.0, a tag ideRegistrador se tornou ideEmpregador, junto com a atualização, removeram a prop tpregistrador.

Essa propriedade está presente no jsonSchema do evtCat, na sped-esocial. Causando uma inconformidade com o Layout da Versão 2.5.0.

Schema com a prop tpregistrador que não deveria mais existir na 2.5.0:
https://github.com/nfephp-org/sped-esocial/blob/master/jsonSchemes/v02_05_00/evtCAT.schema
Linha 22

A solução é remover esse campo que não existe mais.

**Comment by robmachado** [comment]
Na verdade é só deixar como opcional !
