### ISSUE TITLE
s1060 - evtTabAmb - Não existe jsonScheme na versão 2.5.0

### ISSUE THREAD

**Issue by maviniciuus** [nfephp-org/sped-esocial#232]
Na versão 2.5.0, não foi adicionado ainda o jsonScheme do evento s1060, referente a tabelas de ambiente de trabalho.

Na versão 2.4.2 aqui está ele:
https://github.com/nfephp-org/sped-esocial/blob/master/jsonSchemes/v02_04_02/evtTabAmbiente.schema

Na versão 2.5.0 não está na pasta:
https://github.com/nfephp-org/sped-esocial/tree/master/jsonSchemes/v02_05_00

---

A obrigatoriedade dos eventos de SST inicia a partir de Julho de 2019, entretanto, já estou desenvolvendo os meus módulos de SST de acordo com o manual da receita.

Posso abrir um PR com o jsonSchema que eu criei para o s1060, baseado nas especificações atuais da receita?

**Comment by robmachado** [comment]
Pode conferir !
