### ISSUE TITLE
s1060 - evtTabAmb - JSON Scheme divergente da versão 2.5.0

### ISSUE THREAD

**Issue by maviniciuus** [nfephp-org/sped-esocial#235]
Seguem atualizações necessárias:

1 - **dadosambiente.dscamb** minLength é 3 maxlength é 8000;
Referência xsd eSocial 2.5.0; 

2 - **dadosambiente.fatorrisco** não existe mais.
Agora é definidono s2240(CATFR e IPA) ao vincular o s2200 (colaborador) com o s1060(ambiente).
Referência manual e xsd eSocial 2.5.0.

3 - **dadosambiente.localamb** max é 3, pattern é "1|2|3";
Referência manual eSocial 2.5.0.

4 - **dadosambiente.tpinsc** max é 4, required é false, type é [integer, null] pattern "1|3|4";
Referência manual eSocial 2.5.0.

5 - **dadosambiente.nrinsc** max é 14, required é false, type é [string, null];
Referência manual e xsd eSocial 2.5.0.

6 - **dadosambiente.codLotacao** max é 30, min é 1, required é false, type é [string, null]
Referência xsd eSocial 2.5.0.

**Comment by robmachado** [comment]
Opa Legal !! achei também outros erros e estou corrigindo agora !!! 

CONTINUE assim me ajuda bastante :+1:

**Comment by robmachado** [comment]
Pode testar se ainda houver erro desses apresentados me avise ou reabra a ISSUE

**Comment by maviniciuus** [comment]
**dadosambiente.nrinsc** Contínua Obrigatória, assim não permite gerar s1060 preenchendo **dadosambiente.localamb** com o valor 2, Lotações de Terceiros.

> 5 - **dadosambiente.nrinsc** max é 14, required é false, type é [string, null];
> Referência manual e xsd eSocial 2.5.0.

Segundo o manual, preenchimento obrigatório e exclusivo apenas quando **dadosambiente.localamb** for 1 ou 3, não é permitido preencher o campo **dadosambiente.nrinsc** quando é 2

--

Algum motivo para não utilizarmos os patterns?

> 3 - **dadosambiente.localamb** max é 3, pattern é "1|2|3";
> Referência manual eSocial 2.5.0.

> 4 - **dadosambiente.tpinsc** max é 4, required é false, type é [integer, null] pattern "1|3|4";
> Referência manual eSocial 2.5.0.

**Comment by robmachado** [comment]
Então, essas coisas que são "condicionais", ex. se x = 0 então y = true. São complexas demais para fazer na pre-validação e não compensam o esforço. Nesses casos o melhor é deixar para o aplicativo decidir se coloca ou não a informação.
As demais questões vou ajustar !! Novamente obrigado :+1:

**Comment by robmachado** [comment]
Merged !!

**Comment by maviniciuus** [comment]
> Então, essas coisas que são "condicionais", ex. se x = 0 então y = true

Você está certo, essa parte aqui:

> Segundo o manual, preenchimento obrigatório e exclusivo apenas quando dadosambiente.localamb for 1 ou 3, não é permitido preencher o campo dadosambiente.nrinsc quando é 2

Era só pra explicar o porque de tornar **dadosambiente.nrinsc** opcional!

Muito Obrigado!

**Comment by robmachado** [comment]
Sim eu havia entendido, meu amigo. Eu gosto das suas colocações são muito claras e profissionais, gostaria que mais colegas agissem assim. Vou corrigir esse também descAmb !
Mas quando disse "reabrir" estava me referindo aos campos mencionados originalmente, mas como você ainda não faz parte da equipe realmente não tem autoridade para reabrir a issue.

**Comment by robmachado** [comment]
Feito
