### ISSUE TITLE
dscSalVar 2200, 2306

### ISSUE THREAD

**Issue by marceloms163** [nfephp-org/sped-esocial#244]
Tamanho do campo é de 255 caracteres

**Comment by robmachado** [comment]
Corrigido

**Comment by marceloms163** [comment]
Ola, Eu baixei uma atualização da biblioteca agora através do composer, mas ainda consta nos arquivos abaixo "maxLength": 90
jsonSchemes/v02_05_00/evtAdmissao.schema
jsonSchemes/v02_05_00/evtTSVAltContr.schema

**Comment by robmachado** [comment]
**Você esta ERRADO !!** os dois eventos tiveram nos campos "dscsalvar" os limites alterados para 255 caracteres. Pode ser que seus arquivos não tenham sido atualizados pelo composer, por algum outro motivo.

**Comment by marceloms163** [comment]
Me parece que é algum bug no composer, quando eu abro o arquivo diretamente no site do git ele traz correto, porem quando baixo no composer (excluo a pasta e faça um composer install) ele continua vindo errado.

**Comment by robmachado** [comment]
Então eu criei um projeto em branco e instalei a API com o composer, veio tudo correto a ultima versão no repositório.
Tente remover a pasta vendor e o arquivo composer.lock e dê o install novamente.
Para atualizar normalmente eu apenas faço composer update --no-dev --prefer-source (isso enquanto estiver em DEV) depois eu uso composer update --no-dev --prefer-dist

**Comment by marceloms163** [comment]
Ops,,, não sabia que deixar o arquivo composer.lock ele não atualiza direito,, tirei e deu certo, desculpe.

**Comment by robmachado** [comment]
Não por isso ! eu também aprendo algo novo todo dia meu amigo :+1:
