### ISSUE TITLE
Problema no Evento S1000

### ISSUE THREAD

**Issue by Ronney** [nfephp-org/sped-esocial#255]
Estou fazendo a adaptação ao novo layout(2.5), porém sempre dá lote rejeitado no evento S1000. E os erros sempre apontado para os campos indCoop e indConstr. Observei que na classe EvtInfoEmpregador foram feitas algumas atualizações. Inclusive envolvendo esses dois campos.
Porém os códigos das linhas 119 e 125.  Como por exemplo " !empty($cad->indcoop) ? $cad->indcoop : null". 
Não permitem que seja atribuído o valor 0 a eles, pois vai setar como nulo. E Zero é justamente o valor que estou atribuindo nos testes. Desde já agradeço a atenção.

**Comment by robmachado** [comment]
Tem razão !! BUG corrigido :+1: 
Me avise sempre que houver coisas como essa (e com certeza existem outros)
