### ISSUE TITLE
Problema ao tentar enviar um lote de eventos - (S-2240)

### ISSUE THREAD

**Issue by sirwilld** [nfephp-org/sped-esocial#257]
Estava tentando fazer o envio do S-2240, porém quando gero os dados com mais de um evento o id que gera é sempre o mesmo para cada um dos eventos, então o envio falha.

**Comment by robmachado** [comment]
Bom; posso presumir !! diante da falta de detalhes, que você está fazendo algo errado !!

**Comment by sirwilld** [comment]
Difícil passar mais detalhes quando ocorre basicamente isso. Mas vamos lá

Tenho o método que faz o envio direto da minha model onde eu faço um registro para cada lote ou evento a ser enviado.

```php
 public function enviar($dados = [])
    {
        $evento = $this->nome;
        $grupo = $this->grupo;
        $eventos = [];
        try {
            $config = $this->getConfig();
            $certificate = $this->getCertificate();
            $soap = new SoapCurl($certificate);

            foreach ($dados as $dado) {
                $eventos[] = Event::$evento($config, $dado, $certificate);
            }

            $tools = new Tools($this->getConfig(), $this->getCertificate());

            $tools->loadSoapClass($soap);

            $response = $tools->enviarLoteEventos($grupo, $eventos);

            $this->data_envio = date('Y-m-d');
            $this->status = 'enviado';
            $this->retorno = $response;
            $this->store();


            new TMessage('info', $response);
        } catch (\Exception $e) {
            return $e->getMessage();
        }
    }
```

Ou seja a única coisa que faço é tentar enviar. Posso estar usando errado sua lib? Claro que posso. Caso esteja acontecendo me explica o que eu poderia fazer para gerar todos esses eventos e enviar um lote.

Pode ser um erro devido a algum dado errado também? Só gostaria de entender. Desde já agradeço

**Comment by robmachado** [comment]
Dentro do campo $dado no seu script, você tem que indicar o sequencial =
<numero da sequencia>, esse numero é você quem deve controlar para poder
enviar e gerar o ID correto para o evento.

Em geral (mas pode ser que nem sempre) no primeiro envio o sequencial = 1,
nos envios seguintes do mesmo evento receberia o sequencial incrementado +1
e normalmente teria de passar o indRetif = 2 e o numero do recibo anterior
nrRecibo = 'xxxxxxxxxx', pois se trata de uma retificação.

Isso ocorre principalmente nos evento de tabelas como é o caso do
EvtExpRisco.

Roberto

**Comment by robmachado** [comment]
Pessoalmente eu envio apenas um evento por vez !!! mas isso sou eu ...

**Comment by robmachado** [comment]
Quando ocorrer erros você pode pegar a variável $tools->lastRequest que contêm a última requisição enviada para pode analisar o ocorrido, e na propriedade $tools->lastResponse o último retorno recebido.
Isso ajuda no DEBUG
Lembrando a API ainda está em BETA !! (existem bugs ainda)

**Comment by sirwilld** [comment]
Entendi, antes um pouco de tu responder cheguei a pensar que podia ser o sequencial. Mas não tive tempo de testar. Eu também prefiro enviar um evento por vez. Porem o modo que está estruturado o sistema da empresa eu preciso fazer o envio em lote desse evento. Mas pensarei uma maneira de separar isso. Obrigado pela ajuda, sei que está em beta e o que eu puder ajudar eu farei. Abraço.

**Comment by robmachado** [comment]
Sua ajuda fazendo testes já é uma ótima ajuda, mas se conhecer o código ou quiser ajudar na documentação eu agradeço
Abraço :+1:

**Comment by robmachado** [comment]
Se resolver ai  pode encerrar a ISSUE!
