### ISSUE TITLE
Evento S-2245 EvtTreiCap

### ISSUE THREAD

**Issue by ricardo2211** [nfephp-org/sped-esocial#258]
Adicionar campo indTreinAnt

**Comment by robmachado** [comment]
S-2245 v2.5 não tem a tag "indTreinAnt"

**Comment by ricardo2211** [comment]
Desde segunda a tag indTreinAnt começou no ambiente de produção

![image](https://user-images.githubusercontent.com/43911962/58284013-1dc13d00-7d80-11e9-838a-850d6dffe399.png)

**Comment by robmachado** [comment]
UPS !! falha minha ... tá na lista de pendências e na correria nem lembrei disso :+1:

**Comment by robmachado** [comment]
Mas já liberaram os novos XSD ??

**Comment by ricardo2211** [comment]
Sim já liberaram, só que somente estou conseguindo enviar para o ambiente de produção restrita com os novos xsd

**Comment by robmachado** [comment]
Ok já baixei os novos XSD, alterações apenas em EvtExpRisco e EvtTreiCap vou providenciar os ajustes

**Comment by ricardo2211** [comment]
Ao enviar evento para com o ambiente de produção ocorre o seguinte erro 403 - Lote incorreto - Versão do schema não permitida.
Sabe o que pode ser?

**Comment by robmachado** [comment]
Tem duas versões:
1 - as versões dos eventos propriamente ditos
2 - a versão da comunicação 
Essas versões são indicadas no config.json durante o carregamento da classe Tools, em teoria hoje deveria ser:
//Versão do processo de emissão do evento. Informar a versão do aplicativo emissor do evento.
'eventoVersion' => '2.5.0',
//versão do layout do evento
 'serviceVersion' => '1.5.0',

Mas teria de ver o envelope para saber ao certo o que está ocorrendo

**Comment by ricardo2211** [comment]
Estou enviado o seguinte xml.

<eSocial xmlns="http://www.esocial.gov.br/schema/evt/evtTreiCap/v02_05_00">
   <evtTreiCap Id="ID1004498240000002019052317462000001">
      <ideEvento>
         <indRetif>1</indRetif>
         <tpAmb>1</tpAmb>
         <procEmi>1</procEmi>
         <verProc>2_5_0</verProc>
      </ideEvento>
      <ideEmpregador>
         <tpInsc>1</tpInsc>
         <nrInsc>xxxx</nrInsc>
      </ideEmpregador>
      <ideVinculo>
         <cpfTrab>xxx</cpfTrab>
         <nisTrab>xxx</nisTrab>
         <matricula>xxx</matricula>
      </ideVinculo>
      <treiCap>
         <codTreiCap>0501</codTreiCap>
         <infoComplem>
            <dtTreiCap>2019-05-01</dtTreiCap>
            <durTreiCap>1.33</durTreiCap>
            <modTreiCap>1</modTreiCap>
            <tpTreiCap>4</tpTreiCap>
            <ideProfResp>
               <cpfProf>xxx</cpfProf>
               <nmProf>xxx</nmProf>
               <tpProf>1</tpProf>
               <formProf>Bacharel em Engenharia de Software</formProf>
               <codCBO>317110</codCBO>
               <nacProf>1</nacProf>
            </ideProfResp>
         </infoComplem>
      </treiCap>
   </evtTreiCap>

**Comment by robmachado** [comment]
assim não adianta colega !!!

**Comment by ricardo2211** [comment]
Tinha esquecido que para colar xml tem que inserir um código haha

**Comment by ricardo2211** [comment]
`<eSocial xmlns="http://www.esocial.gov.br/schema/evt/evtTreiCap/v02_05_00">
   <evtTreiCap Id="ID1004498240000002019052317462000001">
      <ideEvento>
         <indRetif>1</indRetif>
         <tpAmb>1</tpAmb>
         <procEmi>1</procEmi>
         <verProc>2_5_0</verProc>
      </ideEvento>
      <ideEmpregador>
         <tpInsc>1</tpInsc>
         <nrInsc>xxxx</nrInsc>
      </ideEmpregador>
      <ideVinculo>
         <cpfTrab>xxx</cpfTrab>
         <nisTrab>xxx</nisTrab>
         <matricula>xxx</matricula>
      </ideVinculo>
      <treiCap>
         <codTreiCap>0501</codTreiCap>
         <infoComplem>
            <dtTreiCap>2019-05-01</dtTreiCap>
            <durTreiCap>1.33</durTreiCap>
            <modTreiCap>1</modTreiCap>
            <tpTreiCap>4</tpTreiCap>
            <ideProfResp>
               <cpfProf>xxx</cpfProf>
               <nmProf>xxx</nmProf>
               <tpProf>1</tpProf>
               <formProf>Bacharel em Engenharia de Software</formProf>
               <codCBO>317110</codCBO>
               <nacProf>1</nacProf>
            </ideProfResp>
         </infoComplem>
      </treiCap>
   </evtTreiCap>`

**Comment by robmachado** [comment]
O envelope com o lote eventos seria algo como isso:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v1="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0">
  <soapenv:Header/>
  <soapenv:Body>
    <v1:EnviarLoteEventos>
      <v1:loteEventos>
        <eSocial xmlns="http://www.esocial.gov.br/schema/lote/eventos/envio/v1_1_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          <envioLoteEventos grupo="2">
            <ideEmpregador>
              <tpInsc>1</tpInsc>
              <nrInsc>99999999</nrInsc>
            </ideEmpregador>
            <ideTransmissor>
              <tpInsc>1</tpInsc>
              <nrInsc>99999999999999</nrInsc>
            </ideTransmissor>
            <eventos>
              <evento Id="ID1999999990000002019052318055200001">
                <eSocial xmlns="http://www.esocial.gov.br/schema/evt/evtTreiCap/v02_05_00">
                  <evtTreiCap Id="ID1999999990000002019052318055200001">
                    <ideEvento>
                      <indRetif>1</indRetif>
                      <tpAmb>1</tpAmb>
                      <procEmi>1</procEmi>
                      <verProc>2_5_0</verProc>
                    </ideEvento>
                    <ideEmpregador>
                      <tpInsc>1</tpInsc>
                      <nrInsc>99999999</nrInsc>
                    </ideEmpregador>
                    <ideVinculo>
                      <cpfTrab>11111111111</cpfTrab>
                      <nisTrab>11111111111</nisTrab>
                      <matricula>11111111111</matricula>
                    </ideVinculo>
                    <treiCap>
                      <codTreiCap>2222</codTreiCap>
                      <obsTreiCap>bla bla bla</obsTreiCap>
                      <infoComplem>
                        <dtTreiCap>2018-11-12</dtTreiCap>
                        <durTreiCap>22.4</durTreiCap>
                        <modTreiCap>3</modTreiCap>
                        <tpTreiCap>5</tpTreiCap>
                        <indTreinAnt>N</indTreinAnt>
                        <ideProfResp>
                          <cpfProf>12345678901</cpfProf>
                          <nmProf>Beltrano de Tal</nmProf>
                          <tpProf>1</tpProf>
                          <formProf>bla bla bla</formProf>
                          <codCBO>123456</codCBO>
                          <nacProf>1</nacProf>
                        </ideProfResp>
                      </infoComplem>
                    </treiCap>
                  </evtTreiCap>
                  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
                    <SignedInfo>
                      <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                      <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
                      <Reference URI="">
                        <Transforms>
                          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                          <Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                        </Transforms>
                        <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                        <DigestValue>W6nMDHvnKNX7wL/yrrrAKy4xf14cBOHCh0hlq6fWKR4=</DigestValue>
                      </Reference>
                    </SignedInfo>
                    <SignatureValue>EK4QXRTnftqFKxl2pwskk5o2heElsHdo5xzr42vJggBKF0/aGG2pea+5/iUvjz//zAtqYap2+HfKZ5lTd7oB19FDDitU2DrV7JPKAbbUiUt04DLSBrvRzgnVgLJrcQgKUUU8zHrYKb9XDdbHdusryTkKY4Xs3kUv++HGolJO8r0=</SignatureValue>
                    <KeyInfo>
                      <X509Data>
                        <X509Certificate>MIIEqzCCA5OgAwIBAgIDMTg4MA0GCSqGSIb3DQEBBQUAMIGSMQswCQYDVQQGEwJCUjELMAkGA1UECBMCUlMxFTATBgNVBAcTDFBvcnRvIEFsZWdyZTEdMBsGA1UEChMUVGVzdGUgUHJvamV0byBORmUgUlMxHTAbBgNVBAsTFFRlc3RlIFByb2pldG8gTkZlIFJTMSEwHwYDVQQDExhORmUgLSBBQyBJbnRlcm1lZGlhcmlhIDEwHhcNMDkwNTIyMTcwNzAzWhcNMTAxMDAyMTcwNzAzWjCBnjELMAkGA1UECBMCUlMxHTAbBgNVBAsTFFRlc3RlIFByb2pldG8gTkZlIFJTMR0wGwYDVQQKExRUZXN0ZSBQcm9qZXRvIE5GZSBSUzEVMBMGA1UEBxMMUE9SVE8gQUxFR1JFMQswCQYDVQQGEwJCUjEtMCsGA1UEAxMkTkZlIC0gQXNzb2NpYWNhbyBORi1lOjk5OTk5MDkwOTEwMjcwMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCx1O/e1Q+xh+wCoxa4pr/5aEFt2dEX9iBJyYu/2a78emtorZKbWeyK435SRTbHxHSjqe1sWtIhXBaFa2dHiukT1WJyoAcXwB1GtxjT2VVESQGtRiujMa+opus6dufJJl7RslAjqN/ZPxcBXaezt0nHvnUB/uB1K8WT9G7ES0V17wIDAQABo4IBfjCCAXowIgYDVR0jAQEABBgwFoAUPT5TqhNWAm+ZpcVsvB7malDBjEQwDwYDVR0TAQH/BAUwAwEBADAPBgNVHQ8BAf8EBQMDAOAAMAwGA1UdIAEBAAQCMAAwgawGA1UdEQEBAASBoTCBnqA4BgVgTAEDBKAvBC0yMjA4MTk3Nzk5OTk5OTk5OTk5MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDCgEgYFYEwBAwKgCQQHREZULU5GZaAZBgVgTAEDA6AQBA45OTk5OTA5MDkxMDI3MKAXBgVgTAEDB6AOBAwwMDAwMDAwMDAwMDCBGmRmdC1uZmVAcHJvY2VyZ3MucnMuZ292LmJyMCAGA1UdJQEB/wQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDBTBgNVHR8BAQAESTBHMEWgQ6BBhj9odHRwOi8vbmZlY2VydGlmaWNhZG8uc2VmYXoucnMuZ292LmJyL0xDUi9BQ0ludGVybWVkaWFyaWEzOC5jcmwwDQYJKoZIhvcNAQEFBQADggEBAJFytXuiS02eJO0iMQr/Hi+Ox7/vYiPewiDL7s5EwO8A9jKx9G2Baz0KEjcdaeZk9a2NzDEgX9zboPxhw0RkWahVCP2xvRFWswDIa2WRUT/LHTEuTeKCJ0iF/um/kYM8PmWxPsDWzvsCCRp146lc0lz9LGm5ruPVYPZ/7DAoimUk3bdCMW/rzkVYg7iitxHrhklxH7YWQHUwbcqPt7Jv0RJxclc1MhQlV2eM2MO1iIlk8Eti86dRrJVoicR1bwc6/YDqDp4PFONTi1ddewRu6elGS74AzCcNYRSVTINYiZLpBZO0uivrnTEnsFguVnNtWb9MAHGt3tkR0gAVs6S0fm8=</X509Certificate>
                      </X509Data>
                    </KeyInfo>
                  </Signature>
                </eSocial>
              </evento>
            </eventos>
          </envioLoteEventos>
        </eSocial>
      </v1:loteEventos>
    </v1:EnviarLoteEventos>
  </soapenv:Body>
</soapenv:Envelope>
```

**Comment by robmachado** [comment]
Correções aplicadas

**Comment by ricardo2211** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
   <s:Body>
      <EnviarLoteEventosResponse xmlns="http://www.esocial.gov.br/servicos/empregador/lote/eventos/envio/v1_1_0">
         <EnviarLoteEventosResult>
            <eSocial xmlns="http://www.esocial.gov.br/schema/lote/eventos/envio/retornoEnvio/v1_1_0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
               <retornoEnvioLoteEventos>
                  <ideEmpregador>
                     <tpInsc>1</tpInsc>
                     <nrInsc>XXXX</nrInsc>
                  </ideEmpregador>
                  <ideTransmissor>
                     <tpInsc>1</tpInsc>
                     <nrInsc>xxxx</nrInsc>
                  </ideTransmissor>
                  <status>
                     <cdResposta>201</cdResposta>
                     <descResposta>Lote Recebido com Sucesso.</descResposta>
                  </status>
                  <dadosRecepcaoLote>
                     <dhRecepcao>2019-05-23T18:10:29.93</dhRecepcao>
                     <versaoAplicativoRecepcao>0.1.0-A0352</versaoAplicativoRecepcao>
                     <protocoloEnvio>1.1.201905.0000000000536967394</protocoloEnvio>
                  </dadosRecepcaoLote>
               </retornoEnvioLoteEventos>
            </eSocial>
         </EnviarLoteEventosResult>
      </EnviarLoteEventosResponse>
   </s:Body>
</s:Envelope>`

**Comment by robmachado** [comment]
Uebaaa !!!
