### ISSUE TITLE
Discrepância entre a validação dos eventos S-1040 e S-1060 no eSocial e nos schemas json e XML

### ISSUE THREAD

**Issue by CRitzel** [nfephp-org/sped-esocial#276]
O campo dscFuncao do evento S-1040 está configurado para somente aceitar valores com mais de 8 caracteres no arquivo evtTabFuncao.schema, mas nem o eSocial nem o arquivo evtTabFuncao.xsd pedem por isso.

O mesmo pode ser dito do campo dscAmb do evento S-1060, pois o eSocial não especifica um valor mínimo, mas tanto o evtTabAmbiente.schema quanto o evtTabAmbiente.xsd requerem pelo menos 3 caracteres.

**Comment by robmachado** [comment]
Quanto ao evento S-1040 você está correto o XSD requer entre 1 e 100 caracteres - CORIGGINDO.
Mas o evento S-1060 (TabAmb) o campo dscAmb requer segundo o XSD entre 3 e 8000 caracteres - esta está correto.
