### ISSUE TITLE
Validação S-3000

### ISSUE THREAD

**Issue by CRitzel** [nfephp-org/sped-esocial#278]
O grupo idetrabalhador no arquivo evtExclusao.schema está com 'required = true', mas esse campo só é obrigatório se {tpEvento} corresponder a um dos eventos não periódicos (S-2190 a S-2400) ou um dos eventos periódicos (S-1200, S-1202 ou S-1210). Não informar nos demais casos.

**Comment by robmachado** [comment]
Sim você está correto !! corrigindo.
