### ISSUE TITLE
Situação do Projeto

### ISSUE THREAD

**Issue by douglasoliveiraadv** [nfephp-org/sped-esocial#285]
Senhores,

Sou desenvolvedor PHP e gostaria de saber se o projeto está sendo mantido pela comunidade, se as fases descritas no README.md foram concluídas e se é possível utilizá-lo para empregados domésticos.

Agradeço desde já a quem puder responder!

**Comment by robmachado** [comment]
_gostaria de saber se o projeto está sendo mantido pela comunidade_
**SIM**

_se as fases descritas no README.md foram concluídas_
**ESSAS FASES SÃO DE IMPLEMENTAÇÃO D RECEITA E SIM FORAM EXECUTADAS E ESTÃO ATIVAS**

_se é possível utilizá-lo para empregados domésticos_
**NÃO. O E-SOCIAL POR WEBSERVICE NÃO SE PRESTA A EMPREGADOS DOMESTICOS**

**Comment by douglasoliveiraadv** [comment]
Muito obrigado pelos esclarecimentos!

Apenas mais uma dúvida: não é possível integrar com o eSocial para tratar de domésticos por conta do web service deles ou porque esse projeto nfephp-org/sped-esocial é que ainda não implementa tal funcionalidade?

**Comment by robmachado** [comment]
Simplesmente porque o webservice da RECEITA não implementa a tratativa com domésticos, como eu já havia dito !!
Ou seja NÃO EXISTE ESSA FUNCIONALIDADE para empregados domésticos

**Comment by douglasoliveiraadv** [comment]
Obrigado, novamente, Roberto.

A minha pergunta foi porque encontrei, na web, empresas que oferecem esse tipo de serviço para empregados domésticos (API para integrar com o eSocial), por isso a minha dúvida com relação ao web service. 

Imagino que, para oferecerem essas APIs, eles devem usar algum web service "do governo" para fazer isso. Você sabe responder se existe algum web service da administração pública que faça o registro dos eventos para empregados domésticos?

Agradeço desde já pela ajuda!

**Comment by robmachado** [comment]
Sim esses caras podem ter feito um tipo de CROWLER para acessar o aplicativo da receita "fingindo" ser um browser. Eu não quero nem saber desse tipo de coisa.
E se existe algum webservice para empregados domésticos eu desconheço.

**Comment by douglasoliveiraadv** [comment]
Roberto, sei que o questionamento está fechado, mas continuo em dúvida se é possível ou não usar o webservice do eSocial para empregados domésticos. 

Talvez eu tenha me expressado mal, mas meu intento é usá-lo para empregadores domésticos, para que estes possam registrar seus empregados, emitir as guias de pagamento, registrar o salário do mês e etc.

Insisto no questionamento porque a documentação aborda o empregador doméstico em diversas situações, como neste exemplo que segue em anexo.

![image](https://user-images.githubusercontent.com/47170512/86534044-cf033380-beab-11ea-9ec0-341b14846835.png)

Novamente agradeço pela ajuda e paciência!

**Comment by douglasoliveiraadv** [comment]
Outro ponto da [documentação](https://www.gov.br/esocial/pt-br/documentacao-tecnica/manuais/leiautes-do-novo-esocial-v1-0-beta-pdf.zip) que também me chamou bastante atenção, foi sobre o local de trabalho do empregado doméstico citado na documentação:

![image](https://user-images.githubusercontent.com/47170512/86535177-c5ca9480-beb4-11ea-8bae-3219be5d6d11.png)

Acontece que estou realmente em dúvida, Roberto, porque vi que nas [mensagens](https://www.gov.br/esocial/pt-br/documentacao-tecnica/manuais/mensagenssistemaesocialv1-6.pdf/@@download/file/mensagenssistemaesocialv1-6.pdf) que o webservice pode retornar, consta:

![image](https://user-images.githubusercontent.com/47170512/86535199-f6aac980-beb4-11ea-93f4-77fd1cd5b3cc.png)

**Comment by robmachado** [comment]
Pois é mas esse destaque que você fez te dá uma LUZ:

*1322 - Eventos relacionados a Empregados Domésticos devem ser enviados
exclusivamente pela aplicação web Doméstico.*.

O webservice NÃO pode ser usado para esse tipo de empregado (ou seja
domésticos).

Roberto
