### ISSUE TITLE
SoapException::soapFault

### ISSUE THREAD

**Issue by marceloms163** [nfephp-org/sped-esocial#290]
Ao chamar função SoapException::soapFault esta passando somente 1 parâmetro, mas na classe ele pede 2.

**Comment by robmachado** [comment]
Aponte em quais classes isso ocorre?

**Comment by marceloms163** [comment]
sped-common/src/Soap/SoapCurl.php
linhas: 135, 141
sped-common/src/Soap/SoapNative.php
linhas: 84,86,124,126
sped-esocial/src/Common/Soap/SoapCurl.php
linha: 103,106

**Comment by robmachado** [comment]
OK !! ajustado OBRIGADO  :+1:
