### ISSUE TITLE
Problema no evento S-1000 usando o Layout S-1.0

### ISSUE THREAD

**Issue by Ronney** [nfephp-org/sped-esocial#319]
Boa Tarde, estava tentando enviar o evento S-1000  no ambiente de teste e sempre retornava o seguinte erro: "17 - A estrutura do arquivo XML está em desconformidade com o esquema XSD.The element 'eSocial' in namespace 'http://www.esocial.gov.br/schema/evt/evtInfoEmpregador/v_S_01_00_00' has incomplete content. List of possible elements expected: 'Signature' in namespace 'http://www.w3.org/2000/09/xmld" . Acredito que seja problema na assinatura. Para resolver o problema fui no arquivo "TraitS1000 " e descomentei a  linha relacionada. 

![Captura de tela de 2021-06-28 14-50-39](https://user-images.githubusercontent.com/852457/123682801-de4c6100-d821-11eb-80f5-3fa9f9407aa9.png)

Aparentemente o problema foi resolvido com essa alteração.

**Comment by robmachado** [comment]
Obrigado por avisar !
Ao fazer uma correção, deixei desativada a assinatura, como não estamos usando o PHPUNIT para testes esse tipo de esquecimento passa !
Corrigido !
