### ISSUE TITLE
s2220 validação incorreta

### ISSUE THREAD

**Issue by joefreire** [nfephp-org/sped-esocial#335]
A validação do evtMonit está incorreta, o idevinculo.nistrab pode ser null em caso da categoria do empregado ser 901,903 ou 904

**Comment by matheusfbraga** [comment]
![image](https://user-images.githubusercontent.com/7483320/150453897-5d230c5f-f4b7-40a4-8741-fe0ded69b6d3.png)

O nistrab não esta mais na documentação, ainda não encontrei onde fala sobre a remoção pra saber quando foi, mas acredito que devemos remover do codigo, estou correto? Caso seja pra remover posso organizar um pull request.

**Comment by robmachado** [comment]
o campo nistrab foi removido na versão S1.0 e ao que me lembre não consta mais de nenhum codigo da versão S 1.0
