### ISSUE TITLE
Atualização SST - 1.0 - O que é necessario? 

### ISSUE THREAD

**Issue by MarcosRedR** [nfephp-org/sped-esocial#340]
Os eventos do sst iniciarão dia 13 de outubro para o primeiro grupo. Gostaria de usar e contribuir ao projeto. Podem me ajudar esclarecendo quais arquivos precisam ser atualizados, é somente os schemas e as validações?

**Comment by MarcosRedR** [comment]
Consegui evoluir bastante, só me tirem uma dúvida. O json schema é feito manualmente ou tem conversor do schema para este formato? Acho que é o único ponto que falta para gerar o 2240.

**Comment by robmachado** [comment]
Esses sctipts é que salvam o jsonschema na sua devida pasta, mas antes eles fazem uma validação com um exemplo de stdClass de dados

**Comment by MarcosRedR** [comment]
Obrigado pela lo retorno. Aparentemente o Fake gera correto o 2220 do 1.0s. Estou ajustando o 2240 só ué não havia atentado deste script que gera o json. No caso alterei ele direto. Mas vou modificar tbm este script. O cat me parece atualizado tbm mas vou verificar terminando faço um comit. Valeu

**Comment by andersonls** [comment]
@robmachado @MarcosRedR Os eventos s2200 - EvtAdmissão e s2220 - EvtMonit eu já criei um PR #338 com a atualização para a v1.0.

Também tenho interesse em ir atualizando os demais eventos conforme for utilizando.

**Comment by MarcosRedR** [comment]
Pessoal eu consegui fazer o 2240 funcionar legal eu só não mexi no script que gera o json schema, no caso alterei direto mas é coisa rápida de fazer, terminando faço o pr. O 2220 eu usei o master e me parece já funcionar ok no 1.0. Uma dúvida não é colocada a tag header nos <? XML? Tentei bater com o schema em um serviço online e deu falha nisso.

**Comment by joefreire** [comment]
@MarcosRedR estou tentando fazer a mesma coisa com o s2240,se tiver como você subir a PR pra gente se ajudar, posso adiantar as outras partes

**Comment by robmachado** [comment]
@matheusfbraga Na ISSUE #297  https://github.com/nfephp-org/sped-esocial/issues/297
Está a lista de eventos que ainda não foram transcritos para a versão S 1.0

**Comment by andersonls** [comment]
@MarcosRedR @joefreire Criei o PR #344 com o evento S-2240.

**Comment by joefreire** [comment]
Pessoal eu nem sei se posso falar por aqui mas to precisando de uma consultoria nesses eventos, algum de vocês já conseguiu enviar os eventos? @MarcosRedR @robmachado @andersonls

**Comment by andersonls** [comment]
@joefreire Apenas no ambiente de produção restrita.

**Comment by robmachado** [comment]
Faltam apenas 4 eventos para a conclusão da versão S 1.0 (é claro que podem ainda haver bugs) pois são muitos eventos e com muitos campos neles.

**Comment by robmachado** [comment]
Acredito que todos os eventos psp S 1.0 foram criados !!

**Comment by marcusyoda** [comment]
Boas notícias, os eventos de SST (2210, 2220, 2240) foram homologados em produção, em mais de 3 empresas diferentes do 1º grupo!
Enviei mais de 1000 eventos em produção, vou comparar os ajustes do meu Fork com o Projeto, e ver se tem algo faltando!
Parabéns @robmachado @andersonls e demais envolvidos pelo esforço!
