### ISSUE TITLE
Obrigatoriedade do campo nmRazao na config

### ISSUE THREAD

**Issue by wagner-engel** [nfephp-org/sped-esocial#346]
Hoje a config obriga informar no bloco empregador, além dos campos tpInsc e nrInsc, o campo nmRazao (ver arquivos Common/Factory.php e Commom/Tools.php)

Mas analisando os manuais das versões S1-0 e 2.5, o campo nmRazao não existe nesse bloco.
Analisando também o código via grep, não pude encontrar quem fizesse uso dele dentro da biblioteca.

É necessário manter esse campo? Pergunto pois no caso do layout S1-0, há o caso de declarante pessoa física, que não teriam uma razão social para preencher.

Ou devo nesses casos preencher o próprio nome da pessoa?

**Comment by robmachado** [comment]
Na verdade pode colocar qq coisa (em principio), estou modificando para não exigir mais esse campo pois não é usado na construção dos eventos
