### ISSUE TITLE
Ajustes para NT 03

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-esocial#364]

**Comment by Diegottm** [comment]
Bom dia, primeiramente gostaria de parabenizar pelo projeto!!!  Não sei se esse é o lugar correto para o comentário.
No evento 2210 os campos **hrAcid** e **hrsTrabAntesAcid** somente são obrigatórios se o campo **tpAcid = [1]**.
No evento 2220 o campo **codCateg** não aparece na montagem do xml (Não sei se é algo que estou fazendo errado) e o campo **resAso** não é obrigatório ser informado.
No evento 2240 a tag **epiCompl** não aparece na montagem do xml (Este também não sei se é algo que estou fazendo errado).
Novamente peço desculpas se é algo que estou fazendo errado sou novo na área.

**Comment by robmachado** [comment]
Você deveria ter aberto um novo issue mas sem problema os BUGS foram corrigidos em master
