### ISSUE TITLE
EVENTO-CATFR 2240 - Ajustes inconsistencias com o manual

### ISSUE THREAD

**Issue by marcusyoda** [nfephp-org/sped-esocial#367]
O campo `eficEpi` deve ser opcional, conforme o manual do e-social, nos casos em que a resposta para `utilizEPI` for não `N`

O escopo do campo `epiCompl` não é mais por `epi` na s_1_0_0, e sim por `agNoc`Agente nocivo.

Não pode ser fornecido `docaval` e `dscepi` juntos, somente um ou outro.

**Comment by robmachado** [comment]
Se não estiver resolvido abra novamente esse ISSUE
