### ISSUE TITLE
Pattern Protocolo de Envio

### ISSUE THREAD

**Issue by arismarioneves** [nfephp-org/sped-esocial#383]
O patterm atual do protocolo de envios dos eventos v_S_01_00_00 estão incorretos.

Modelo do pattern do protocolo de envio:  1.2.202201.0000000000112233444.

Atual:
<xs:pattern value="[1]{1}\.\d{1}\.\d{19}" />

Novo:
<xs:pattern value="[1]{1}\.\d{1}\.\d{6}\.\d{12}" />

**Comment by robmachado** [comment]
**Da onde você tirou isso ??**
Nos xsds mais recentes "Esquemas XSD v. S-1.0 - NT 03/2021" continua igual sem essa alteração que você menciona.

**Comment by marcusyoda** [comment]
Bom dia, aqui continua enviando normalmente em produção e produção restrita sem alterações!

**Comment by robmachado** [comment]
Obrigado Marcus, também sei disso. Mas quero saber da onde o colega tirou esse informação.

**Comment by arismarioneves** [comment]
O problema foi encontrado quando eu tento fazer a Retificação de uma transmissão. Uso o indRetif = 2 e envio o protocolo recebido na transmissão Original. O modelo de protocolo que eu estou recebendo está neste padrão (1.2.202201.0000000000112233444), então eu só conseguir retificar modificando o pattern.

**Comment by robmachado** [comment]
Você está retificando um evento emitido originalmente pela versão 2.5 ??

**Comment by arismarioneves** [comment]
Não, estou usando a versão S-1.0.

**Comment by robmachado** [comment]
Precisamos conferir isso e ver qual é a estruturas dos recibos retornados para outros emitentes antes de chegarmos a alguma conclusão sobre esse caso.
Não é possível simplesmente alterar o XSD ! tem algo estranho ai ... (pode ser a Receita federal que tem se comportado cada vez pior nesse governo)

**Comment by robmachado** [comment]
Então .. estou conferindo e parece que alguns recibos tem o formato do XSD e outros estão vindo diferentes estou vendo com um colega para ver se tem algum motivo para isso. Pois ser for esse realmente o caso. Não adianta colocar esse pattern que você menciona no xsd pois alguns estão nesse formato e outros NÃO ai vai falhar em um caso ou outro

**Comment by robmachado** [comment]
@arismarioneves Você também deveria ver os recibos que tem ai pois se alguns estiverem em um formato e outros em outro formato vai voltar a ter erros na validação do XSD

**Comment by arismarioneves** [comment]
Opa, muito obrigado @marcusyoda. Agora faz sentido.

**Comment by robmachado** [comment]
Grande Marcus !! valeu !!
