### ISSUE TITLE
Correção no Evento S2399

### ISSUE THREAD

**Issue by haeliomarcio** [nfephp-org/sped-esocial#410]
Alguns campos estão obrigatório, mais eles não existem no layout S2399.

Erro: [dtnascto] A propriedade dtnascto \u00e9 obrigat\u00f3rio\n;

[dtadm] A propriedade dtadm \u00e9 obrigat\u00f3rio\n;

[codcateg] NULL encontrado, mas uma string \u00e9 obrigat\u00f3rio"'

**Comment by robmachado** [comment]
Na versão S1.0 
Não existe [dtnascto] e esse campo não é requerido !!!!
Não existe [dtadm] e esse campo não é requerido !!!!

[codcateg] NULL encontrado, mas uma string \u00e9 obrigat\u00f3rio"'
   O primeiro ideTrabSemVinculo/codcateg é OPCIONAL
   O segundo remunOutrEmpr/codcateg é OBRIGATÓRIO

Não tem o que corrigir !!!!

**Comment by haeliomarcio** [comment]
Olá Roberto,

Só o [codcateg] que está obrigatório, e na documentação, ele se diz opcional.
