### ISSUE TITLE
erro ao enviar S2200

### ISSUE THREAD

**Issue by andrex47** [nfephp-org/sped-esocial#416]
ao enviar servidores estatutários nesse evento, ocorre um erro devido a propriedade nula remuneração, porém, essa não deve ser enviada para essa classe de trabalhadores

**Comment by robmachado** [comment]
Você pode ser um pouco mais detalhado em qual campo ocorre o erro .

**Comment by andrex47** [comment]
linha 1807 do arquivo TraitS2200, eu fiz a seguinte modificação para resolver
if ($std->remuneracao) {
foi para
if (isset($std->remuneracao)) {
o próximo condicional na linha 1830 está com o mesmo problema
adicionar a verificação isset dentro desse if resolve

**Comment by haeliomarcio** [comment]
Olá @andrex47, estou passando pelo mesmo problema.
@robmachado tudo bem?

Basta ir no arquivo TraitS2200.php e aplicar o isset na condicional da linha 1807 e 1830.
Irá resolver o erro da remuneracao e duracao. 

Grato amigo.

**Comment by andrex47** [comment]
muito bom @haeliomarcio , eu apliquei as correções e estou continuando a fazer testes na S2200, encontrei um novo problema, criei uma pull request aqui no projeto para serem adicionadas as correções
