### ISSUE TITLE
número de recibo

### ISSUE THREAD

**Issue by andrex47** [nfephp-org/sped-esocial#418]
como obter o número de recibo de 23 caracteres após o envio de um lote de eventos?

**Comment by andersonls** [comment]
Você deve consultar o lote com o número do protocolo recebido no envio do lote. Se o lote foi processado com sucesso e E-social irá retornar o recibo.

Veja nos exemplos o FaketestEnvia.php e FaketestConsultaLote.php.

**Comment by andrex47** [comment]
muito obrigado
