### ISSUE TITLE
Elemento nrRecCatOrig - s2210

### ISSUE THREAD

**Issue by arismarioneves** [nfephp-org/sped-esocial#419]
O elemento "**nrRecCatOrig**" (s2210) não obrigatório, somente quando o elemento "**tpCat**" for igual a "2" ou "3".

**Comment by andersonls** [comment]
Qual versão do layout você está utilizando? 

Na versão 1.0 este campo é obrigatório quanto informado o pai "catOrigem", neste caso é só não informar o "catOrigem". Exemplo:

```
$std->catorigem = new \stdClass();
$std->catorigem->nrreccatorig = '1.1.1234567890123456789';
```

**Comment by arismarioneves** [comment]
Valeu @andersonls. No meu caso é a versão 1.0. sua informações me ajudou.
