### ISSUE TITLE
nrinsc com 8 caracteres no xml de resposta

### ISSUE THREAD

**Issue by andrex47** [nfephp-org/sped-esocial#420]
No grupo ideEmpregador estou recebendo um xml de resposta com um número de 8 caracteres. em vez de 14 que deveria ser correspondente do CNPJ da instituição. Estou tendo problemas no envio da 2200 dizendo para verificar se o evento de cadastro de empregador foi enviado. É pra ser isso mesmo?

**Comment by andersonls** [comment]
Na resposta de qual evento? No evento S-1000 (cadastro inicial do empregador), na maioria dos casos o CNPJ informado tem apenas os primeiros 8 caracteres e não o CNPJ completo. Conforme o manual do e-social:

> e tpInsc for igual a [1], deve ser um número de CNPJ válido. Neste caso, deve ser informada apenas a raiz/base (8 posições), exceto se a natureza jurídica do declarante for igual a 101-5, 104-0, 107-4, 116-3 ou 134-1, situação em que o campo deve ser preenchido com o CNPJ completo (14 posições).

**Comment by andrex47** [comment]
todos os eventos enviados retornam, então é para ser esse o comportamento corrento dele mesmo. Obrigado

**Comment by andrex47** [comment]
estou verificando o envio de todos os eventos da instituição e somente consigo enviar o S-1000 e S-1005 e S-1010, todos os outros eventos retornam com status de processamento pedindo para verificar se já foi enviado o cadastro de empregador, nesse caso o S-1000, verifiquei se o CNPJ estava batendo e o XML é construído em todos eles com os 8 caracteres, que é pra ser o correto, alguma ideia do que pode estar acontecendo?
