### ISSUE TITLE
O Campo tpplanrp do evento S2200 não está sendo criado ao passar valor ZERO.

### ISSUE THREAD

**Issue by haeliomarcio** [nfephp-org/sped-esocial#422]
Caros,

O campo tpplanrp do Evento S-2200 não está sendo criado no XML ao passar valor zero.
$std->vinculo->infoestatutario->tpplanrp = 0; //Opcional

**Comment by andersonls** [comment]
Qual versão do layout você está utilizando?

**Comment by haeliomarcio** [comment]
Versão S.1.0.0

Grato

**Comment by andersonls** [comment]
Testei aqui e está funcionando. Veja se está com a biblioteca atualizada e como você está informando esse campo. Por exemplo, não é possível informar o campo infoceletista e infoestatutario ao mesmo tempo. Se informar os dois, só o primeiro é criado no XML.

**Comment by haeliomarcio** [comment]
Atualizei o master e deu tudo certo @andersonls, grato.
