### ISSUE TITLE
EPIs - S-2240

### ISSUE THREAD

**Issue by arismarioneves** [nfephp-org/sped-esocial#431]
Não tem sido possível transmitir o evento S2240, pois o eSocial sempre retorna:

_Grupo 'Equipamentos de Proteção Individual - EPI' não deve ser preenchido._

Quando o código do Agente Nocivo é diferente de: **09.01.001**

Nos casos em que os EPIs não são informados.

**Comment by robmachado** [comment]
Acredito que era uma verificação IMPROPRIA que fazia isso !! essa condição foi removida !
