### ISSUE TITLE
Campo codinccprp não cria no Evento S1010

### ISSUE THREAD

**Issue by haeliomarcio** [nfephp-org/sped-esocial#433]
Olá Caros @andersonls e @robmachado , o campo codinccprp ao passar para o XML, o mesmo não cria no XML.

Na TraitS1010 o campo codinccprp não consta.

Na documentação do eSocial, esse campo é opcional. AO enviar a Fase 2, o eSocial está procurando o campo codinccprp nas rubricas.

**Comment by robmachado** [comment]
Verifique se está ok agora !
