### ISSUE TITLE
Consulta por recibo

### ISSUE THREAD

**Issue by edolfuchs** [nfephp-org/sped-esocial#442]
Pessoal, alguem já conseguiu usar algum dos métodos: downloadEventosPorNrRecibo, consultarEventosEmpregador, consultarEventosTrabalhador?

Quando tento usar me retorna o erro:

1018 - CNPJ do solicitante não consta no cadastro da RFB

Estou pensando se é problema no esocial ou de algum dado incorreto.

**Comment by robmachado** [comment]
O CNPJ pode ter 8 digitos
