### ISSUE TITLE
Consulta Qualificação Cadastral

### ISSUE THREAD

**Issue by mayder** [nfephp-org/sped-esocial#446]
Estou tentando encontrar aqui nos exemplos se existe algum apenas para fazer a consulta na qualificação cadastral, alguém saberia me informar se existe algum exemplo assim?

**Comment by robmachado** [comment]
Questionamentos desse tipo devem ser feitos no grupo NFePHP ou na sla do Gitter e não abrindo uma ISSUE!

Respondendo sua pergunta, a que eu saiba a qualificação cadastral está disponível apenas via pagina WEB e é limitada em relação  ao numero de consultas permitidas.

**Comment by mayder** [comment]
Obrigado Roberto.
