### ISSUE TITLE
Nova versão S.1.1 em produção em  19/03/2023

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-esocial#464]
- verificar
- ajustar
- subir

**Comment by joefreire** [comment]
O evento s2240 esta utilizando o schema da versão s.1.1 hoje dia 16/01/2023 retornando o erro
`A estrutura do arquivo XML está em desconformidade com o esquema XSD. The element 'epi' in namespace 'http://www.esocial.gov.br/schema/evt/evtExpRisco/v_S_01_00_00' has invalid child element 'dscEPI' in namespace 'http://www.esocial.gov.br/schema/evt/evtExpRisco/v_S_01_00_00'. List of possible elements expected: 'docAval' in namespace 'http://www.esocial.gov.br/schema/evt/evtExpRisco/v_S_01_00_00'.`
ACHO que é algum erro no sistema do governo

**Comment by robmachado** [comment]
não necessariamente, pode ser um erro na construção do xml, ou xsd desatualizado tem que conferir

**Comment by robmachado** [comment]
Nova versão S 1.1.0 entra em produção em março, mas já temos as novas versões preparadas no sistema, devem estar ok fora algum bug ou esquecimento
