### ISSUE TITLE
Consultoria

### ISSUE THREAD

**Issue by matheusfbraga** [nfephp-org/sped-esocial#476]
![image](https://user-images.githubusercontent.com/7483320/212330920-152a800c-f85a-41f0-aff3-d947e9a5a79f.png)

Estou a procura de um freelancer para uma consultoria (paga por hora).

O sistema esta pronto, realizando envios normalmente, porem muitas empresas retornam erros como esse. A documentação do governo não é muito objetiva, gostaria de conversar com quem ja enfrentou essas divergencias.

**Comment by robmachado** [comment]
Veja isso não é um problema da biblioteca (aparentemente) e sim um problema relacionado a sequencia de operações.
Pesquisando na WEB encontrei essa pagina veja se pode ajuda-lo https://atendimento.onsafety.com.br/erro-esocial-1557
É importante que quem dá o suporte em aplicações que enviam o eSocial tenha feito bons cursos sobre o funcionamento do eSocial.

Esses cursos não são "baratos" mas também não são tão caros nos que impeça de faze-los. 
Quando erros ocorrem é necessário confirmar que os eventos anteriores estão lá e foram aceitos corretamente. Sei de casos em que não foram enviados os eventos de admissão e queriam enviar os pagamentos e dava evidentemente esse tipo de erro. Apenas você que tem os dados em mãos pode investigar o que pode estar acontecendo. Confirmando os dados seja no site do eSocial seja nos próprios XML enviados, lembrando que existem muitas camadas que podem causar erros inclusive a própria Receita Federal.
