### ISSUE TITLE
Erro Transmissão Módelo v_S_01_01_00

### ISSUE THREAD

**Issue by arismarioneves** [nfephp-org/sped-esocial#486]
Poderiam me informar o que seria, este retorno, na tentativa de fazer uma transmissão de uma S-2240 para o eSocial:

A estrutura do arquivo XML está em desconformidade com o esquema XSD.
The element 'eSocial' in namespace 'http://www.esocial.gov.br/schema/evt/evtExpRisco/v_S_01_01_00' has incomplete content. List of possible elements expected: 'Signature' in namespace 'http://www.w3.org/2000/09/xmldsig#'.

**Comment by robmachado** [comment]
É obvio está faltando a assinatura ! Tinha um esquecimento na Trait2240, que ainda estava em modo teste e por isso não assinava. Agora deve estar corrigido
