### ISSUE TITLE
Tag obrigatória em exemplo do evento S1200

### ISSUE THREAD

**Issue by ArthurPerdSantos** [nfephp-org/sped-esocial#491]
Bom dia, referente ao arquivo Fake_s1200_EvtRemun.php, notei uma tag marcada como obrigatória, porém não consta na documentação do layout, se trata da $std->dmdev[0]->ideestablot[0]->remunperapur[0]->itensremun[0]->vrunit. Teria como me confirmar se esta não deveria estar ali, ou a documentação está incorreta? Estou com um problema de layout e não encontrei uma solução ainda.

**Comment by robmachado** [comment]
Gostaria que todos que informam ISSUES fossem claros como você foi isso facilita muito.
Deve estar resolvido !

**Comment by ArthurPerdSantos** [comment]
Haha, acontece, muito obrigado pelo esclarecimento.
