### ISSUE TITLE
Eventos totalizadores

### ISSUE THREAD

**Issue by philipe-vieira** [nfephp-org/sped-esocial#495]
Bom dia. 
Recemente comecei a integrar a biblioteca sped-esocial à minha aplicação. Tive a necessidade de implementar o evento de totalizadores (S-5001, S-5002, S-5003, S-5011, S-5012, S-5013), mas vi não tem esses eventos na biblioteca. Numa busca rápida vi que os arquivos Traits foram removido no commit [ajuste S-2240 e inclusão S-1202](https://github.com/nfephp-org/sped-esocial/pull/357/commits/9970bee5c8f2d905beec88c5ab6435cc43515b6a). Ainda há alguma forma de enviar esses eventos com a biblioteca, mesmo que implementando novamente? Ou teve alguma motivação maior pra ser retirado?

**Comment by robmachado** [comment]
Estes eventos se não me engano são retornos da Receita

**Comment by philipe-vieira** [comment]
Sim. minha equipe está precisando deste retorno para a conferência dos valores de cada trabalhador. Tendo em vista que, pela quantidade de trabalhadores, se torna inviável a conferência pela plataforma do eSocial.
Teriamos que implementar toda a lógica destes eventos novamente?

**Comment by philipe-vieira** [comment]
De fato, nesses eventos as informações  em questão são RETORNADAS e não ENVIADAS. Contudo é preciso enviar 'algo' para ter o retorno, não?

**Comment by robmachado** [comment]
Sim são as consultas

**Comment by philipe-vieira** [comment]
Revendo a documentação para desenvolvedores do eSocial consegui entender sua colocação. O totalizador virá na consulta pelo retorno do processamento do evento na tag `tot`, ainda não tinha me atentado que existia essa tag.
Estarei fechando esta issue.
Obrigado amigo.
