### ISSUE TITLE
Bloco "idetrabalhador" do evtRemun (S1200) não pode ser gerado externamente.

### ISSUE THREAD

**Issue by ArthurPerdSantos** [nfephp-org/sped-esocial#499]
Boa tarde, estou tendo problema com o EvtRemun (S1200), alguns clientes são estrangeiros e se faz necessária a criação do bloco "$std->idetrabalhador->infocomplem", porém mesmo fazendo a criação do "idetrabalhador" esses dados não são enviados.

Verifiquei o XML e notei que mesmo antes da criação do "idetrabalhador" o campo cpfTrab, já era mostrado dentro dele. Imagino que essa criação "automática" do bloco "idetrabalhador", está bloqueando a criação de um novo. Como não encontrei nada no meu código, verifiquei a biblioteca, e notei que nos arquivos docs/EvtRemun.md e src/Factories/Traits/TraitS1200.php, é falada dessa construção. Não sei exatamente como isso pode ser resolvido, mas preciso que esse bloco não seja criado diretamente na lib.

**Comment by robmachado** [comment]
Arthur recomendo que olhe o XSD do evento EvtRemun, o campo cpfTrab é OBRIGATÓRIO edeve conter um numero de CPF válido !! que será validado com o xsd e tem que ter 11 digitos.

**Comment by ArthurPerdSantos** [comment]
No caso o meu problema é que não consigo enviar um bloco que deve ser interno do "idetrabalhador", como pode ver esse é a estrutura do xml que tenho registrado de envio.

<ideTrabalhador>
<cpfTrab> cpf do sócio </cpfTrab>
</ideTrabalhador>

porém, a estrutura do código é essa: 
        $std = new \stdClass();
        $std->indretif = 1;  // 1 - original, 2 - retificação
        $std->indapuracao = 1;  // 1 - mensal, 2 - anual
        $std->perapur = $periodoApurado;
        $std->cpftrab = $dadosSocio->pessoa->cpf;

        $std->idetrabalhador = new \stdClass();
        $std->idetrabalhador->infocomplem = new \stdClass();
        $std->idetrabalhador->infocomplem->nmtrab = ucwords(strtolower($dadosSocio->pessoa->name));
        $std->idetrabalhador->infocomplem->dtnascto = $dadosSocio->pessoa->birthDate;
Tive que manter o cpftrab fora, caso eu adicione diretamente no bloco a própria lib aponta o erro.

Esse é o bloco que preciso enviar:
![image](https://github.com/nfephp-org/sped-esocial/assets/71047214/11c63892-5b16-4442-98ea-d09f1aa26fa9)

**Comment by robmachado** [comment]
Rapaz !! olha o exemplo ....

$std->infocomplem = new \stdClass()

Não existe $std->idetrabalhador !! Todo o evento é relativo ao trabalhador !!
