### ISSUE TITLE
Iniciar nova versão S 1.2 - entra em vigor em 20/11/2023

### ISSUE THREAD

**Issue by robmachado** [nfephp-org/sped-esocial#504]

**Comment by samueldietrick** [comment]
tem previsão pra implementação de uma breve forme de uso?

**Comment by robmachado** [comment]
A forma de uso não mudou desde a versão 2.5 as exemplos FAKE indicam como
usar para enviar os eventos e como realizar as consultas.

Roberto

**Comment by robmachado** [comment]
Todos os eventos foram criados para a versão S 1.2 devem haver bugs é necessário testar
