### ISSUE TITLE
Utilização de procuração

### ISSUE THREAD

**Issue by IGOROLIVEIRA** [nfephp-org/sped-esocial#559]
Olá

Existe a possibilidade de usar o certificado de uma pessoa, que não é o responsável pela entidade, mas foi data a ela uma procuração eletrônica para o envio dos dados do eSocial?

Caso sim, como fazer?

**Comment by robmachado** [comment]
Sim é possível fazer consultas e envios ao eSocial, usando uma procuração eletrônica autorizando outros a operarem o sistema.
Mas este ambiente é para tratar ISSUES e não responder perguntas sobre o funcionamento do eSocial. Por favor faça sua pergunta ao grupo do google NFePHP https://groups.google.com/g/nfephp

**Comment by Pelesyno** [comment]
Sim, através de procuração feita no site do eCAC - Centro Virtual de Atendimento (fazenda.gov.br)<https://cav.receita.fazenda.gov.br/autenticacao/login> tem um menu escrito PROCURAÇÕES.



________________________________
De: IGOR AFONSO OLIVEIRA RUAS ***@***.***>
Enviado: terça-feira, 2 de julho de 2024 14:49
Para: nfephp-org/sped-esocial ***@***.***>
Cc: Subscribed ***@***.***>
Assunto: [nfephp-org/sped-esocial] Utilização de procuração (Issue #559)


Olá

Existe a possibilidade de usar o certificado de uma pessoa, que não é o responsável pela entidade, mas foi data a ela uma procuração eletrônica para o envio dos dados do eSocial?

Caso sim, como fazer?
