### ISSUE TITLE
ErrorException in Tools.php line 138: file_put_contents(/var/www/sped/sped-esocial/local/signed.xml): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by alexassuncao** [nfephp-org/sped-esocial#78]
https://github.com/nfephp-org/sped-esocial/blob/master/src/Tools.php - linha 138

 file_put_contents('/var/www/sped/sped-esocial/local/signed.xml', $evt->toXML());

**Comment by robmachado** [comment]
Atualizado, linha extra removida
